In [94]:
import pandas as pd
import numpy as np

ENDERECO_DADOS = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'

try:
    # Lendo os dados do arquivo CSV
    df_roubos = pd.read_csv(ENDERECO_DADOS, encoding='iso-8859-1', sep=';')
    
    # Exibindo as primeiras linhas do DataFrame para verificar os dados
    print(df_roubos['regiao'].unique())
except Exception as e:
    print(f"Erro ao ler os dados: {e}")

<StringArray>
[                      'Capital',            'Baixada Fluminense',
                      'Interior', 'Grande NiterÃÂÃÂÃÂÃÂ³i',
                'Grande Niterói']
Length: 5, dtype: str

In [95]:
# Tratamento de Dados

try:
    df_roubos = df_roubos[['cisp', 'regiao', 'munic', 'roubo_veiculo']]

    # corrigindo erro de digitação
    correcao = df_roubos['regiao'].str.startswith('Grande Niter', na=False)
    df_roubos.loc[correcao, 'regiao'] = 'Grande Niterói'

    print(df_roubos['regiao'].unique())

except Exception as e:
    print(f"Erro ao tratar os dados: {e}")

<StringArray>
['Capital', 'Baixada Fluminense', 'Interior', 'Grande Niterói']
Length: 4, dtype: str

In [96]:
# Processando as informações

try:
    df_roubos = df_roubos.groupby(['cisp','regiao','munic'], as_index=False)['roubo_veiculo'].sum()
    display(df_roubos)

except Exception as e:
    print(f"Erro ao processar os dados: {e}")

     cisp    regiao                 munic  roubo_veiculo
0       1   Capital        Rio de Janeiro            573
1       4   Capital        Rio de Janeiro           2201
2       5   Capital        Rio de Janeiro           1365
3       6   Capital        Rio de Janeiro           4632
4       7   Capital        Rio de Janeiro           2016
..    ...       ...                   ...            ...
141   159  Interior  Cachoeiras de Macacu            286
142   165  Interior           Mangaratiba            500
143   166  Interior        Angra dos Reis            970
144   167  Interior                Paraty            106
145   168  Interior             Rio Claro             63

[146 rows x 4 columns]

In [97]:
# Calculando a medidas: Array, Media, Mediana, Total e Quartil
try:
    array_roubos = df_roubos['roubo_veiculo']

    media = np.mean(array_roubos)
    mediana = np.median(array_roubos)
    total = np.sum(array_roubos)
    q1 = np.percentile(array_roubos, 25)
    q3 = np.percentile(array_roubos, 75)

    print(f"Media: {media}")
    print(f"Mediana: {mediana}")
    print(f"Total: {total}")
    print(f"Quartil 1: {q1}")
    print(f"Quartil 3: {q3}")


except Exception as e:
    print(f"Erro ao calcular as medidas: {e}")

Media: 4907.698630136986
Mediana: 945.5
Total: 716524
Quartil 1: 93.25
Quartil 3: 7342.25

In [98]:
# Identificando os maiores e menores valores
try:
    # Maiores
    df_maiores = df_roubos[df_roubos['roubo_veiculo'] > q3].copy()

    # Menores
    df_menores = df_roubos[df_roubos['roubo_veiculo'] < q1].copy()

    # Adicionando a coluna de flags
    df_maiores['flags'] = 'mais'
    df_menores['flags'] = 'menos'

    # Concatenando os DataFrames
    df_roubos_flags = pd.concat([df_maiores, df_menores], ignore_index=True)
    display(df_roubos_flags)

except Exception as e:
    print(f"Erro ao identificar os maiores e menores valores: {e}")

    cisp    regiao                  munic  roubo_veiculo  flags
0     17   Capital         Rio de Janeiro           7674   mais
1     20   Capital         Rio de Janeiro           9033   mais
2     21   Capital         Rio de Janeiro          19637   mais
3     22   Capital         Rio de Janeiro          15106   mais
4     23   Capital         Rio de Janeiro          10759   mais
..   ...       ...                    ...            ...    ...
69   155  Interior  São Sebastião do Alto             29  menos
70   156  Interior   Santa Maria Madalena             47  menos
71   157  Interior      Trajano de Morais             21  menos
72   158  Interior             Bom Jardim             21  menos
73   168  Interior              Rio Claro             63  menos

[74 rows x 5 columns]

In [99]:
# Exportando os Dados
try:
    df_roubos_flags.to_csv('dados_tratados.csv', index=False)
    # exportando para Excel df_roubos_flags.to_excel('dados_tratados.xlsx', index=False) e instalar a biblioteca openpyxl: pip install openpyxl
    df_roubos_flags.to_excel('dados_tratados.xlsx', index=False)


except Exception as e:
    print(f"Erro ao exportar os dados: {e}")